variables:
    DOCKERFILE_FOLDER: "opencl/"
  
# Stages
stages:
  - lint
  - repository tagging
  - build
  - deploy

# Scripts
include:
  - /.gitlab-ci-scripts.yml

# Jobs
# Only for 64-bit vivante arch

default:
  # retry failed jobs, since Docker is not very stable when running many jobs in parallel
  retry: 2

dockerfile-lint-opencl:
  extends: .dockerfile-lint
  stage: lint

tag-opencl:
  extends: .tag
  before_script:
    - export MAJOR="${DEBIAN_MAJOR}"
    - export MINOR="${DEBIAN_MINOR}"
    - export PATCH="${DEBIAN_PATCH}"
  stage: repository tagging
  variables:
    SAMPLE_NAME: opencl

docker-build-opencl-arm64v8:
  extends: .docker-build
  before_script:
    - export MAJOR="${DEBIAN_MAJOR}"
    - export MINOR="${DEBIAN_MINOR}"
    - export PATCH="${DEBIAN_PATCH}"
  variables:
    BASE_NAME: debian
    IMAGE_NAME: arm64v8-sample-opencl-vivante
    IMAGE_ARCH: linux/arm64/v8
    IMAGE_TAG: ${DEBIAN_RELEASE_NUMBER}-${DEBIAN_RELEASE}
    CROSS_TC_IMAGE_TAG: ${DEBIAN_RELEASE_NUMBER}-${DEBIAN_RELEASE}
  stage: build

docker-deploy-opencl-arm64v8:
  extends: .docker-deploy
  before_script:
    - export MAJOR="${DEBIAN_MAJOR}"
    - export MINOR="${DEBIAN_MINOR}"
    - export PATCH="${DEBIAN_PATCH}"
  variables:
    IMAGE_NAME: arm64v8-sample-opencl-vivante
  stage: deploy