# Stages
stages:
  - build

# Scripts
include:
  - /.gitlab-ci-scripts.yml

# Jobs
# Only for 64-bit vivante arch
docker-build-opencl-arm64v8:
  extends: .docker-build
  before_script:
    - export MAJOR="${WAYLAND_BASE_VIVANTE_MAJOR}"
    - export MINOR="${WAYLAND_BASE_VIVANTE_MINOR}"
    - export PATCH="${WAYLAND_BASE_VIVANTE_PATCH}"
  variables:
    BASE_NAME: wayland-base-vivante
    IMAGE_NAME: arm64v8-sample-opencl-vivante
    IMAGE_ARCH: linux/arm64/v8
    IMAGE_TAG: ${DEBIAN_RELEASE}-latest
    DOCKERFILE_FOLDER: "opencl/"
  stage: build
