variables:
  DOCKERFILE_FOLDER: "opencl/"

# Stages
stages:
  - lint
  - repository tagging
  - build

# Scripts
include:
  - /.gitlab-ci-scripts.yml

# Jobs
# Only for 64-bit vivante arch

dockerfile-lint-opencl:
  extends: .dockerfile-lint
  stage: lint

tag-opencl:
  extends: .tag
  before_script:
    - export MAJOR="${WAYLAND_BASE_VIVANTE_MAJOR}"
    - export MINOR="${WAYLAND_BASE_VIVANTE_MINOR}"
    - export PATCH="${WAYLAND_BASE_VIVANTE_PATCH}"
  stage: repository tagging
  variables:
    SAMPLE_NAME: opencl

docker-build-opencl-arm64v8:
  extends: .docker-build
  before_script:
    - export MAJOR="${WAYLAND_BASE_VIVANTE_MAJOR}"
    - export MINOR="${WAYLAND_BASE_VIVANTE_MINOR}"
    - export PATCH="${WAYLAND_BASE_VIVANTE_PATCH}"
  variables:
    BASE_NAME: wayland-base-vivante
    IMAGE_NAME: arm64v8-sample-opencl-vivante
    IMAGE_ARCH: linux/arm64/v8
    IMAGE_TAG: ${DEBIAN_RELEASE}-latest
  stage: build
