variables:
  DOCKERFILE_FOLDER: "dbus/tools/"

# Stages
stages:
  - lint
  - repository tagging
  - build
  - build-multiarch

# Scripts
include:
  - /.gitlab-ci-scripts.yml

# Jobs

default:
  # retry failed jobs, since Docker is not very stable when running many jobs in parallel
  retry: 2

dockerfile-lint-dbus-tools:
  extends: .dockerfile-lint
  stage: lint

tag-dbus-tools:
  extends: .tag
  before_script:
    - export MAJOR="${DEBIAN_MAJOR}"
    - export MINOR="${DEBIAN_MINOR}"
    - export PATCH="${DEBIAN_PATCH}"
  stage: repository tagging
  variables:
    SAMPLE_NAME: dbus-tools

docker-build-dbus-tools:
  extends: .docker-build
  before_script:
    - export MAJOR="${DEBIAN_MAJOR}"
    - export MINOR="${DEBIAN_MINOR}"
    - export PATCH="${DEBIAN_PATCH}"
  variables:
    BASE_NAME: debian
    IMAGE_NAME: arm32v7-sample-dbus-tools
    IMAGE_ARCH: linux/arm/v7
    IMAGE_TAG: ${DEBIAN_RELEASE_NUMBER}-${DEBIAN_RELEASE}
  stage: build

docker-build-dbus-tools-arm64v8:
  extends: .docker-build
  before_script:
    - export MAJOR="${DEBIAN_MAJOR}"
    - export MINOR="${DEBIAN_MINOR}"
    - export PATCH="${DEBIAN_PATCH}"
  variables:
    BASE_NAME: debian
    IMAGE_NAME: arm64v8-sample-dbus-tools
    IMAGE_ARCH: linux/arm64/v8
    IMAGE_TAG: ${DEBIAN_RELEASE_NUMBER}-${DEBIAN_RELEASE}
  stage: build

docker-build-dbus-tools-multiarch:
  extends: .docker-build-multiarch
  variables:
    IMAGE_NAME: sample-dbus-tools
    IMAGE_NAME_32: arm32v7-sample-dbus-tools
    IMAGE_NAME_64: arm64v8-sample-dbus-tools
  stage: build-multiarch
