variables:
  DOCKERFILE_FOLDER: "adc/"

# Stages
stages:
  - lint
  - repository tagging
  - build
  - build-multiarch
  - deploy
  - deploy-multiarch

# Scripts
include:
  - /.gitlab-ci-scripts.yml

# Jobs

default:
  # retry failed jobs, since Docker is not very stable when running many jobs in parallel
  retry: 2

dockerfile-lint-adc:
  extends: .dockerfile-lint
  stage: lint

tag-adc:
  extends: .tag
  before_script:
    - export MAJOR="${DEBIAN_MAJOR}"
    - export MINOR="${DEBIAN_MINOR}"
    - export PATCH="${DEBIAN_PATCH}"
  stage: repository tagging
  variables:
    SAMPLE_NAME: adc

docker-build-adc:
  extends: .docker-build
  before_script:
    - export MAJOR="${DEBIAN_MAJOR}"
    - export MINOR="${DEBIAN_MINOR}"
    - export PATCH="${DEBIAN_PATCH}"
  variables:
    BASE_NAME: debian
    IMAGE_NAME: arm32v7-sample-adc
    IMAGE_ARCH: linux/arm/v7
    IMAGE_TAG: ${DEBIAN_RELEASE_NUMBER}-${DEBIAN_RELEASE}
    CROSS_TC_IMAGE_ARCH: armhf
    GCC_PREFIX: arm-linux-gnueabihf
  stage: build

docker-build-adc-arm64v8:
  extends: .docker-build
  before_script:
    - export MAJOR="${DEBIAN_MAJOR}"
    - export MINOR="${DEBIAN_MINOR}"
    - export PATCH="${DEBIAN_PATCH}"
  variables:
    BASE_NAME: debian
    IMAGE_NAME: arm64v8-sample-adc
    IMAGE_ARCH: linux/arm64/v8
    IMAGE_TAG: ${DEBIAN_RELEASE_NUMBER}-${DEBIAN_RELEASE}
    CROSS_TC_IMAGE_ARCH: arm64
    GCC_PREFIX: aarch64-linux-gnu
  stage: build

docker-build-adc-multiarch:
  extends: .docker-build-multiarch
  variables:
    IMAGE_NAME: sample-adc
    IMAGE_NAME_32: arm32v7-sample-adc
    IMAGE_NAME_64: arm64v8-sample-adc
  stage: build-multiarch

docker-deploy-adc:
  extends: .docker-deploy
  before_script:
    - export DEBIAN_RELEASE_APPEND="-${DEBIAN_RELEASE}"
    - export MAJOR="${DEBIAN_MAJOR}"
    - export MINOR="${DEBIAN_MINOR}"
    - export PATCH="${DEBIAN_PATCH}"
  variables:
    IMAGE_NAME: arm32v7-sample-adc
  stage: deploy

docker-deploy-adc-arm64v8:
  extends: .docker-deploy
  before_script:
    - export DEBIAN_RELEASE_APPEND="-${DEBIAN_RELEASE}"
    - export MAJOR="${DEBIAN_MAJOR}"
    - export MINOR="${DEBIAN_MINOR}"
    - export PATCH="${DEBIAN_PATCH}"
  variables:
    IMAGE_NAME: arm64v8-sample-adc
  stage: deploy

docker-deploy-adc-multiarch:
  extends: .docker-deploy-multiarch
  before_script:
    - export DEBIAN_RELEASE_APPEND="-${DEBIAN_RELEASE}"
    - export MAJOR="${DEBIAN_MAJOR}"
    - export MINOR="${DEBIAN_MINOR}"
    - export PATCH="${DEBIAN_PATCH}"
  variables:
    IMAGE_NAME: sample-adc
    IMAGE_NAME_32: arm32v7-sample-adc
    IMAGE_NAME_64: arm64v8-sample-adc
  stage: deploy-multiarch
