variables:
  DOCKERFILE_FOLDER: "python-qml/"

# Stages
stages:
  - lint
  - repository tagging
  - build
  - build-multiarch

# Scripts
include:
  - /.gitlab-ci-scripts.yml

# Jobs

dockerfile-lint-qt5-python-qml:
  extends: .dockerfile-lint
  stage: lint

tag-qt5-python-qml:
  extends: .tag
  before_script:
    - export MAJOR="${QT5_WAYLAND_MAJOR}"
    - export MINOR="${QT5_WAYLAND_MINOR}"
    - export PATCH="${QT5_WAYLAND_PATCH}"
  stage: repository tagging
  variables:
    SAMPLE_NAME: qt5-python-qml

tag-qt5-python-qml-arm64v8-vivante:
  extends: .tag
  before_script:
    - export MAJOR="${QT5_WAYLAND_VIVANTE_MAJOR}"
    - export MINOR="${QT5_WAYLAND_VIVANTE_MINOR}"
    - export PATCH="${QT5_WAYLAND_VIVANTE_PATCH}"
  stage: repository tagging
  variables:
    SAMPLE_NAME: qt5-python-qml-arm64v8-vivante

docker-build-qt5-python-qml:
  extends: .docker-build
  before_script:
    - export MAJOR="${QT5_WAYLAND_MAJOR}"
    - export MINOR="${QT5_WAYLAND_MINOR}"
    - export PATCH="${QT5_WAYLAND_PATCH}"
  variables:
    BASE_NAME: qt5-wayland
    IMAGE_NAME: arm32v7-sample-qt5-python-qml
    IMAGE_ARCH: linux/arm/v7
    IMAGE_TAG: ${DEBIAN_RELEASE_NUMBER}
  stage: build

docker-build-qt5-python-qml-arm64v8:
  extends: .docker-build
  before_script:
    - export MAJOR="${QT5_WAYLAND_MAJOR}"
    - export MINOR="${QT5_WAYLAND_MINOR}"
    - export PATCH="${QT5_WAYLAND_PATCH}"
  variables:
    BASE_NAME: qt5-wayland
    IMAGE_NAME: arm64v8-sample-qt5-python-qml
    IMAGE_ARCH: linux/arm64/v8
    IMAGE_TAG: ${DEBIAN_RELEASE_NUMBER}
  stage: build

docker-build-qt5-python-qml-arm64v8-vivante:
  extends: .docker-build
  before_script:
    - export MAJOR="${QT5_WAYLAND_VIVANTE_MAJOR}"
    - export MINOR="${QT5_WAYLAND_VIVANTE_MINOR}"
    - export PATCH="${QT5_WAYLAND_VIVANTE_PATCH}"
  variables:
    BASE_NAME: qt5-wayland-vivante
    IMAGE_NAME: arm64v8-sample-qt5-python-qml-vivante
    IMAGE_ARCH: linux/arm64/v8
    IMAGE_TAG: ${DEBIAN_RELEASE_NUMBER}
  stage: build
  # arm64 with Vivante(ARG BASE_NAME=qt5-wayland-vivante) is currently not
  # supported as python3-pyside2.qtgui is not co-installable with libqt5qui5-gles
  # See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=974101
  allow_failure: true

docker-build-qt5-python-qml-multiarch:
  extends: .docker-build-multiarch
  variables:
    IMAGE_NAME: sample-qt5-python-qml
    IMAGE_NAME_32: arm32v7-sample-qt5-python-qml
    # IMAGE_NAME_64: arm64v8-sample-qt5-python-qml-vivante
    # Use the non-vivante package until it's working
    # arm64 with Vivante(ARG BASE_NAME=qt5-wayland-vivante) is currently not
    # supported as python3-pyside2.qtgui is not co-installable with libqt5qui5-gles
    # See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=974101
    IMAGE_NAME_64: arm64v8-sample-qt5-python-qml
  stage: build-multiarch
