# Stages
stages:
  - build
  - build-multiarch

# Scripts
include:
  - /.gitlab-ci-scripts.yml

# Jobs
docker-build-collectd:
  extends: .docker-build
  before_script:
    - export MAJOR="${DEBIAN_MAJOR}"
    - export MINOR="${DEBIAN_MINOR}"
    - export PATCH="${DEBIAN_PATCH}"
  variables:
    BASE_NAME: base
    IMAGE_NAME: arm32v7-sample-collectd
    IMAGE_ARCH: linux/arm/v7
    IMAGE_TAG: ${DEBIAN_RELEASE}-latest
    DOCKERFILE_FOLDER: "grafana/"
  stage: build

docker-build-collectd-arm64v8:
  extends: .docker-build
  before_script:
    - export MAJOR="${DEBIAN_MAJOR}"
    - export MINOR="${DEBIAN_MINOR}"
    - export PATCH="${DEBIAN_PATCH}"
  variables:
    BASE_NAME: base
    IMAGE_NAME: arm64v8-sample-collectd
    IMAGE_ARCH: linux/arm64/v8
    IMAGE_TAG: ${DEBIAN_RELEASE}-latest
    DOCKERFILE_FOLDER: "grafana/"
  stage: build

docker-build-collectd-multiarch:
  extends: .docker-build-multiarch
  variables:
    IMAGE_NAME: sample-collectd
    IMAGE_NAME_32: arm32v7-sample-collectd
    IMAGE_NAME_64: arm64v8-sample-collectd
  stage: build-multiarch
