# this override brings up Grafana on a local display
version: "2.4"
services:
  weston:
    environment:
      - ACCEPT_FSL_EULA=1
    container_name: weston
    # For armhf (i.MX 6- and i.MX 7-based modules) use this image:
    #image: torizon/weston:1
    # For i.MX 8-based modules use this image:
    image: torizon/weston-vivante:1
    # Required to get udev events from host udevd via netlink
    network_mode: host
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /run/udev
        target: /run/udev
    cap_add:
      - CAP_SYS_TTY_CONFIG
    # Add device access rights through cgroup...
    device_cgroup_rules:
      # ... for tty0
      - 'c 4:0 rmw'
      # ... for tty7
      - 'c 4:7 rmw'
      # ... for /dev/input devices
      - 'c 13:* rmw'
      - 'c 199:* rmw'
      # ... for /dev/dri devices
      - 'c 226:* rmw'
  
  kiosk:
    container_name: kiosk
    # For armhf (i.MX 6- and i.MX 7-based modules) use this image:
    #image: torizon/arm32v7-debian-kiosk-mode-browser:1
    # For i.MX 8-based modules use this image:
    image: torizon/arm64v8-debian-kiosk-mode-browser:1
    command: --window-mode http://grafana:3000
    security_opt:
      - seccomp:unconfined    
    networks:
      - frontend
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /var/run/dbus
        target: /var/run/dbus
      - type: bind
        source: /dev/dri
        target: /dev/dri
    depends_on:
      - weston
      - grafana
      - influxdb
    shm_size: '256mb'
    device_cgroup_rules:
      # ... for /dev/dri devices
      - 'c 226:* rmw'
