variables:
  DOCKERFILE_FOLDER: "sht31/kiosk/"

# Stages
stages:
  - lint
  - repository tagging
  - build
  - build-multiarch

# Scripts
include:
  - /.gitlab-ci-scripts.yml

# Jobs

dockerfile-lint-uart-sht31-kiosk:
  extends: .dockerfile-lint
  stage: lint

tag-uart-sht31-kiosk:
  extends: .tag
  before_script:
    - export MAJOR="${CHROMIUM_MAJOR}"
    - export MINOR="${CHROMIUM_MINOR}"
    - export PATCH="${CHROMIUM_PATCH}"
  stage: repository tagging
  variables:
    SAMPLE_NAME: uart-sht31-kiosk

docker-build-uart-sht31-kiosk:
  extends: .docker-build
  before_script:
    - export MAJOR="${CHROMIUM_MAJOR}"
    - export MINOR="${CHROMIUM_MINOR}"
    - export PATCH="${CHROMIUM_PATCH}"
  variables:
    BASE_NAME: chromium
    IMAGE_NAME: arm32v7-sample-uart-sht31-kiosk
    IMAGE_ARCH: linux/arm/v7
    IMAGE_TAG: ${DEBIAN_RELEASE_NUMBER_LEGACY}
  stage: build

docker-build-uart-sht31-kiosk-arm64v8:
  extends: .docker-build
  before_script:
    - export MAJOR="${CHROMIUM_MAJOR}"
    - export MINOR="${CHROMIUM_MINOR}"
    - export PATCH="${CHROMIUM_PATCH}"
  variables:
    BASE_NAME: chromium
    IMAGE_NAME: arm64v8-sample-uart-sht31-kiosk-vivante
    IMAGE_ARCH: linux/arm64/v8
    IMAGE_TAG: ${DEBIAN_RELEASE_NUMBER_LEGACY}
  stage: build

docker-build-uart-sht31-kiosk-multiarch:
  extends: .docker-build-multiarch
  variables:
    IMAGE_NAME: sample-uart-sht31-kiosk
    IMAGE_NAME_32: arm32v7-sample-uart-sht31-kiosk
    IMAGE_NAME_64: arm64v8-sample-uart-sht31-kiosk-vivante
  stage: build-multiarch
