version: "2.4"
services:
  weston1:
    image: torizon/weston-vivante:2
    command: --developer weston-launch --tty=/dev/tty7 --user=torizon -- --seat=seat1 --shell=kiosk-shell.so
    # EULA required to run imx8 vivante graphic drivers
    # Pre-accept as we ask the user accept the EULA already.
    environment:
      - ACCEPT_FSL_EULA=1
    # Required to get udev events from host udevd via netlink
    network_mode: host
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /run/udev
        target: /run/udev
    cap_add:
      - CAP_SYS_TTY_CONFIG
    # Add device access rights through cgroup...
    device_cgroup_rules:
      # ... for tty0
      - 'c 4:0 rmw'
      # ... for tty7
      - 'c 4:7 rmw'
      # ... for /dev/input devices
      - 'c 13:* rmw'
      - 'c 199:* rmw'
      # ... for /dev/dri devices
      - 'c 226:* rmw'

  app1:
    image: torizon/weston-vivante:2
    command: weston-flower
    # EULA required to run imx8 vivante graphic drivers
    # Pre-accept as we ask the user accept the EULA already.
    environment:
      - ACCEPT_FSL_EULA=1
    # Required to get udev events from host udevd via netlink
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /dev/dri
        target: /dev/dri
      - type: bind
        source: /dev/galcore
        target: /dev/galcore
    user: torizon
    # Add device access rights through cgroup...
    device_cgroup_rules:
      - 'c 199:* rmw'
      # ... for /dev/dri devices
      - 'c 226:* rmw'
    depends_on:
      - weston1

  weston2:
    image: torizon/weston-vivante:2
    command: --developer weston-launch --tty=/dev/tty8 --user=torizon -- --seat=seat0 --use-pixman --shell=kiosk-shell.so
    # EULA required to run imx8 vivante graphic drivers
    # Pre-accept as we ask the user accept the EULA already.
    environment:
      - ACCEPT_FSL_EULA=1
    # Required to get udev events from host udevd via netlink
    network_mode: host
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /run/udev
        target: /run/udev
    cap_add:
      - CAP_SYS_TTY_CONFIG
   # Add device access rights through cgroup...
    device_cgroup_rules:
      # ... for tty0
      - 'c 4:0 rmw'
      # ... for tty8
      - 'c 4:8 rmw'
      # ... for /dev/input devices
      - 'c 13:* rmw'
      - 'c 199:* rmw'
      # ... for /dev/dri devices
      - 'c 226:* rmw'
    depends_on:
      - weston1
      - app1

  app2:
    image: torizon/weston-vivante:2
    command: weston-simple-egl
    # EULA required to run imx8 vivante graphic drivers
    # Pre-accept as we ask the user accept the EULA already.
    environment:
      - ACCEPT_FSL_EULA=1
      - WAYLAND_DISPLAY=wayland-1
    # Required to get udev events from host udevd via netlink
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /dev/dri
        target: /dev/dri
      - type: bind
        source: /dev/galcore
        target: /dev/galcore
    user: torizon
    # Add device access rights through cgroup...
    device_cgroup_rules:
      - 'c 199:* rmw'
      # ... for /dev/dri devices
      - 'c 226:* rmw'
    depends_on:
      - weston1
      - app1
      - weston2
