# Stages
stages:
  - build
  - build-multiarch

# Scripts
include:
  - /.gitlab-ci-scripts.yml

# Jobs
docker-build-gstreamer-simple-pipeline:
  extends: .docker-build
  before_script:
    - export MAJOR="${WAYLAND_BASE_MAJOR}"
    - export MINOR="${WAYLAND_BASE_MINOR}"
    - export PATCH="${WAYLAND_BASE_PATCH}"
  variables:
    BASE_NAME: wayland-base
    IMAGE_NAME: arm32v7-sample-gstreamer-simple-pipeline
    IMAGE_ARCH: linux/arm/v7
    IMAGE_TAG: ${DEBIAN_RELEASE}-latest
    DOCKERFILE_FOLDER: "gstreamer/bash/simple-pipeline/"
  stage: build

docker-build-gstreamer-simple-pipeline-arm64v8:
  extends: .docker-build
  before_script:
    - export MAJOR="${WAYLAND_BASE_VIVANTE_MAJOR}"
    - export MINOR="${WAYLAND_BASE_VIVANTE_MINOR}"
    - export PATCH="${WAYLAND_BASE_VIVANTE_PATCH}"
  variables:
    BASE_NAME: wayland-base-vivante
    IMAGE_NAME: arm64v8-sample-gstreamer-simple-pipeline-vivante
    IMAGE_ARCH: linux/arm64/v8
    IMAGE_TAG: ${DEBIAN_RELEASE}-latest
    DOCKERFILE_FOLDER: "gstreamer/bash/simple-pipeline/"
  stage: build

docker-build-gstreamer-simple-pipeline-multiarch:
  extends: .docker-build-multiarch
  variables:
    IMAGE_NAME: sample-gstreamer-simple-pipeline
    IMAGE_NAME_32: arm32v7-sample-gstreamer-simple-pipeline
    IMAGE_NAME_64: arm64v8-sample-gstreamer-simple-pipeline-vivante
  stage: build-multiarch
