version: "2.4"
services:

  weston:
    image: torizon/weston-vivante:3
    # Accept the EULA required to run imx8 vivante graphic drivers
    environment:
     - ACCEPT_FSL_EULA=1
    # Required to get udev events from host udevd via netlink
    network_mode: host
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /run/udev
        target: /run/udev
    cap_add:
      - CAP_SYS_TTY_CONFIG
    # Add device access rights through cgroup...
    device_cgroup_rules:
      # ... for tty0
      - 'c 4:0 rmw'
      # ... for tty1
      - 'c 4:1 rmw'
      # ... for tty7
      - 'c 4:7 rmw'
      # ... for /dev/input devices
      - 'c 13:* rmw'
      # ... for /dev/galcore
      - 'c 199:* rmw'
      # ... for /dev/dri devices
      - 'c 226:* rmw'
    command: --developer --tty=/dev/tty7
    healthcheck:
        test: ["CMD", "test", "-S", "/tmp/1000-runtime-dir/wayland-0"]
        interval: 5s
        timeout: 4s
        retries: 6
        start_period: 10s

  wayland:
    depends_on:
      weston:
        condition: service_healthy
    image: <your-username>/gst_example
    volumes:
       - /tmp:/tmp 
       - /dev:/dev
    restart: on-failure
