version: "2.4"
services:
  grafana:
    container_name: grafana
    depends_on:
      - influxdb
    networks:
      - backend
      - frontend
    volumes:
      - "grafana-storage:/var/lib/grafana"
    ports:
      - "3000:3000"
    links:
      - influxdb
    image: grafana/grafana:6.7.1

  influxdb:
    container_name: influxdb
    networks:
      - backend
    volumes:
      - "influxdb-grafana:/var/lib/influxdb"
    image: influxdb:1.7.10

  weather:
    build:
      context: .
      args:
        IMAGE_ARCH: linux/arm
        TOOLCHAIN_ARCH: armhf
        PKG_ARCH: armhf
    container_name: weather
    depends_on:
      - influxdb
    networks:
      - backend
      - frontend

networks:
  backend:
    internal: true
  frontend:
    internal: false

volumes:
  grafana-storage:
  influxdb-grafana: