variables:
  DOCKERFILE_FOLDER: "gps/python/"

# Stages
stages:
  - lint
  - repository tagging
  - build
  - build-multiarch

# Scripts
include:
  - /.gitlab-ci-scripts.yml

# Jobs

dockerfile-lint-uart-gps-python:
  extends: .dockerfile-lint
  stage: lint

tag-uart-gps-python:
  extends: .tag
  before_script:
    - export MAJOR="${DEBIAN_MAJOR}"
    - export MINOR="${DEBIAN_MINOR}"
    - export PATCH="${DEBIAN_PATCH}"
  stage: repository tagging
  variables:
    SAMPLE_NAME: uart-gps-python

docker-build-uart-gps-python:
  extends: .docker-build
  before_script:
    - export MAJOR="${DEBIAN_MAJOR}"
    - export MINOR="${DEBIAN_MINOR}"
    - export PATCH="${DEBIAN_PATCH}"
  variables:
    BASE_NAME: base
    IMAGE_NAME: arm32v7-sample-uart-gps-python
    IMAGE_ARCH: linux/arm/v7
    IMAGE_TAG: ${DEBIAN_RELEASE}-latest
  stage: build

docker-build-uart-gps-python-arm64v8:
  extends: .docker-build
  before_script:
    - export MAJOR="${DEBIAN_MAJOR}"
    - export MINOR="${DEBIAN_MINOR}"
    - export PATCH="${DEBIAN_PATCH}"
  variables:
    BASE_NAME: base
    IMAGE_NAME: arm64v8-sample-uart-gps-python
    IMAGE_ARCH: linux/arm64/v8
    IMAGE_TAG: ${DEBIAN_RELEASE}-latest
  stage: build

docker-build-uart-gps-python-multiarch:
  extends: .docker-build-multiarch
  variables:
    IMAGE_NAME: sample-uart-gps-python
    IMAGE_NAME_32: arm32v7-sample-uart-gps-python
    IMAGE_NAME_64: arm64v8-sample-uart-gps-python
  stage: build-multiarch
