variables:
  DOCKERFILE_FOLDER: "opencv/"

# Stages
stages:
  - lint
  - repository tagging
  - build
  - deploy

# Scripts
include:
  - /.gitlab-ci-scripts.yml

# Jobs
# Only for 64-bit vivante arch

dockerfile-lint-opencv:
  extends: .dockerfile-lint
  stage: lint

tag-opencv:
  extends: .tag
  before_script:
    - export MAJOR="${WAYLAND_BASE_VIVANTE_MAJOR}"
    - export MINOR="${WAYLAND_BASE_VIVANTE_MINOR}"
    - export PATCH="${WAYLAND_BASE_VIVANTE_PATCH}"
  stage: repository tagging
  variables:
    SAMPLE_NAME: opencv

docker-build-opencv-arm64v8:
  extends: .docker-build
  before_script:
    - export MAJOR="${WAYLAND_BASE_VIVANTE_MAJOR}"
    - export MINOR="${WAYLAND_BASE_VIVANTE_MINOR}"
    - export PATCH="${WAYLAND_BASE_VIVANTE_PATCH}"
  variables:
    BASE_NAME: wayland-base-vivante
    IMAGE_NAME: arm64v8-sample-opencv-vivante
    IMAGE_ARCH: linux/arm64/v8
    IMAGE_TAG: ${DEBIAN_RELEASE}-latest
  stage: build

docker-deploy-opencv-arm64v8:
  extends: .docker-deploy
  before_script:
    - export MAJOR="${WAYLAND_BASE_VIVANTE_MAJOR}"
    - export MINOR="${WAYLAND_BASE_VIVANTE_MINOR}"
    - export PATCH="${WAYLAND_BASE_VIVANTE_PATCH}"
  variables:
    IMAGE_NAME: arm64v8-sample-opencv-vivante
  stage: deploy